title: "Shivani Awati"
description: "Data Analytics • Data Science • Cloud (AWS, Oracle)"
url: "https://shivaniawati.github.io"   # no trailing slash
baseurl: "/portfolio"                    # if you ever move to root, change to ""

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: neon

markdown: kramdown
permalink: pretty
paginate: 5

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

author:
  name: "Shivani Awati"
  bio: "Data Analytics & Data Science • Python • SQL • Power BI • AWS • Oracle Cloud"
  location: "DFW • Remote"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/YOUR-HANDLE"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/shivaniawati"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:YOUR_EMAIL"

# Optional: keep README out of the site build
exclude:
  - README.md

